import { ChartNoAxesCombined, LucideProps } from "lucide-react";
import {
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpDown,
  ArrowUpFromLine,
  Award,
  BadgeCheck,
  Banknote,
  BarChart2,
  Bomb,
  Calculator,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  CircleDollarSign,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  ClipboardPaste,
  Clock,
  Coins,
  Compass,
  Copy,
  Crown,
  Diamond,
  DollarSign,
  Download,
  FileText,
  Flame,
  FolderOpen,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  Grid3x3,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  Instagram,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  ListOrdered,
  Loader2,
  Lock,
  LockKeyhole,
  LogOut,
  Menu,
  MessageCircle,
  MoreHorizontal,
  Pen,
  Percent,
  Pizza,
  Play,
  RefreshCw,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Spade,
  Sparkles,
  Star,
  TableProperties,
  Target,
  Ticket,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  User,
  UserCircle,
  UserPen,
  Users,
  Video,
  Volume2,
  Wallet,
  WalletCards,
  X,
} from "lucide-react";
import type { ComponentType } from "react";

export const LUCIDE_ICON_MAP: Record<string, ComponentType<LucideProps>> = {
  // mdi / solar / mingcute / lucide prefixed
  "mdi:close": X,
  "lucide:x": X,
  "mdi:chevron-right": ChevronRight,
  "mdi:chevron-left": ChevronLeft,
  "mdi:information": Info,
  "mdi:loading": Loader2,
  "mdi:share-variant": Share2,
  "mdi:alert-circle": AlertCircle,
  "mingcute:lock-fill": LockKeyhole,
  "solar:copy-linear": Copy,
  "solar:medal-star-bold": Award,
  "solar:dollar-minimalistic-bold-duotone": DollarSign,
  "solar:ticket-linear": Ticket,

  // no-prefix legacy custom names
  achievement: Award,
  "claim-reset": RefreshCw,
  "claim-warning": AlertTriangle,

  // custom: prefixed aliases
  "custom:account-verified": BadgeCheck,
  "custom:arcade": Gamepad2,
  "custom:baccarat": Spade,
  "custom:back": ArrowLeft,
  "custom:bet-history": ClipboardList,
  "custom:bingo": Grid3x3,
  "custom:blackjack": Spade,
  "custom:bonus": Gift,
  "custom:calculator": Calculator,
  "custom:calendar": Calendar,
  "custom:cash": Banknote,
  "custom:casino": Diamond,
  "custom:chart": BarChart2,
  "custom:commission-calculator": Calculator,
  "custom:copied": ClipboardCheck,
  "custom:crash": TrendingDown,
  "custom:cup": Trophy,
  "custom:dashboard": LayoutDashboard,
  "custom:deposit": ArrowDownToLine,
  "custom:dollars": DollarSign,
  "custom:double": ChevronsRight,
  "custom:enhanced-rtp": TrendingUp,
  "custom:explore": Compass,
  "custom:facebook-messenger": MessageCircle,
  "custom:facebook": Share2,
  "custom:favorites": Heart,
  "custom:feature-buy": ShoppingCart,
  "custom:free-spin": Gamepad2,
  "custom:game-shows": Tv,
  "custom:game": Gamepad2,
  "custom:global": Globe,
  "custom:google": Globe,
  "custom:greatest-win": Trophy,
  "custom:handball": Target,
  "custom:headphone-2": Headphones,
  "custom:headphone": Headphones,
  "custom:heart": Heart,
  "custom:home": Home,
  "custom:hot": Flame,
  "custom:info": Info,
  "custom:instagram": Instagram,
  "custom:jackpot": Coins,
  "custom:keno": Hash,
  "custom:latest-win": TrendingUp,
  "custom:leaderboard": ListOrdered,
  "custom:left-close": LayoutDashboard,
  "custom:legal": FileText,
  "custom:live-casino": Video,
  "custom:lock": Lock,
  "custom:logo-m": Gem,
  "custom:logo": Gem,
  "custom:logout": LogOut,
  "custom:max-win": TrendingUp,
  "custom:megaways": LayoutGrid,
  "custom:menu-2": Menu,
  "custom:menu": Menu,
  "custom:metamask": Wallet,
  "custom:mines": Bomb,
  "custom:more": MoreHorizontal,
  "custom:new": Sparkles,
  "custom:no-records": FolderOpen,
  "custom:password-check": KeyRound,
  "custom:paste": ClipboardPaste,
  "custom:pen": Pen,
  "custom:person": User,
  "custom:play": Play,
  "custom:plinko": CircleDot,
  "custom:poker": Spade,
  "custom:profile-achievements": Award,
  "custom:profile-avatar-edit": UserPen,
  "custom:profile-avatar": UserCircle,
  "custom:profile-recent-top-games": BarChart2,
  "custom:profile-referral-program": Users,
  "custom:profile-security": ShieldCheck,
  "custom:profile-stats": BarChart2,
  "custom:profile": User,
  "custom:public": Globe,
  "custom:question": HelpCircle,
  "custom:recent-top": TrendingUp,
  "custom:recent": Clock,
  "custom:referral-bonus": Gift,
  "custom:referral": Share2,
  "custom:refresh": RefreshCw,
  "custom:rewards": Star,
  "custom:rollover": RefreshCw,
  "custom:roulette": CircleDot,
  "custom:percent": Percent,
  "custom:rtp": ChartNoAxesCombined,
  "custom:bounty": CircleDollarSign,
  "custom:scratch": Layers,
  "custom:security": Shield,
  "custom:setting-2": SlidersHorizontal,
  "custom:setting": Settings,
  "custom:settings": Settings,
  "custom:share": Share2,
  "custom:shield": Shield,
  "custom:speaker": Volume2,
  "custom:sports": Trophy,
  "custom:stats": BarChart2,
  "custom:suarez-signature": User,
  "custom:swap": ArrowLeftRight,
  "custom:table-game": TableProperties,
  "custom:table-games": TableProperties,
  "custom:target": Target,
  "custom:telegram-2": Send,
  "custom:telegram": Send,
  "custom:tick-square": CheckSquare,
  "custom:tournament": Trophy,
  "custom:transactions": ArrowLeftRight,
  "custom:tx": ArrowUpDown,
  "custom:user": User,
  "custom:video-poker": Video,
  "custom:vip": Crown,
  "custom:wallet": WalletCards,
  "custom:warning": AlertTriangle,
  "custom:support": User,
  "custom:whats-app": MessageCircle,
  "custom:withdraw": ArrowUpFromLine,
  "custom:bonus-store": ShoppingBag,
  "custom:bonus-lock": LockKeyhole,
  "custom:achievements_finsh": CheckCircle2,
  "custom:check_in": CalendarCheck,
  "custom:check_in_logo": CalendarCheck,
  "custom:date_left": ChevronLeft,
  "custom:date_right": ChevronRight,
  "custom:down_load": Download,
  "custom:app": Settings,
  "custom:check": Check,
  "custom:gift": Gift,
  "custom:pizza": Pizza,
  "custom:dollar": CircleDollarSign,
};
